title:  LeadsCalendar project docs
description: >- # this means to ignore newlines until "baseurl:"
  This is a small static website that hosts documentation for LeadsCalendar project
  It is meant to serve as a guide in creating the project.
theme: just-the-docs

baseurl: /documentingrandomness
url: http://hismaj3sty.github.io

